[metrics]
go_process = true

[api]
address = ":5001"

[postgres]
dsn = "postgres://postgres:postgres@127.0.0.1:5432/ge_celo_data"

[chain]
rpc_endpoint = "https://forno.celo.org"
# Defaults to Celo mainnet
# At the moment only support Celo based blockchains
chainid = 42220

[bootstrap]
# This will bootstrap the cache on which addresses to track
# Grassroots Economics specific registries that autoload all other smart contracts
ge_registries = [
    "0xd1FB944748aca327a1ba036B082993D9dd9Bfa0C",
    "0x0cc9f4fff962def35bb34a53691180b13e653030",
]

[jetstream]
endpoint = "nats://127.0.0.1:4222"
id = "celo-indexer-1"
